services:
    srhinow_themecontent.listener.insert_tags:
        class: Srhinow\ThemecontentBundle\EventListener\InsertTagsListener
        arguments:
            - "@contao.framework"
        public: true
    srhinow_themecontent.listener.dca:
        class: Srhinow\ThemecontentBundle\EventListener\DcaListener
        arguments:
            - "@contao.framework"
            - "@database_connection"
        public: true
